export const PRODUCTS_DISCOUNTS = 'PRODUCTS_DISCOUNTS';
export const NOTES_DISCOUNTS = 'NOTES_DISCOUNTS';
export const BILL_DISCOUNTS = 'BILL_DISCOUNTS';
export const COURTESY_APPLY_PRODUCTS = 'COURTESY_APPLY_PRODUCTS';
export const COURTESY_APPLY_NOTES = 'COURTESY_APPLY_NOTES';
export const COURTESY_APPLY_BILL = 'COURTESY_APPLY_BILL';
