export const SET_PERCENT = 'SET_PERCENT';
export const SET_QUANTITY = 'SET_QUANTITY';
export const COURTESY_APPLY_NOTES = 'COURTESY_APPLY_NOTES';
export const COURTESY_APPLY_BILL = 'COURTESY_APPLY_BILL';
